[features]
seeds = false
skip-lint = false
[programs.localnet]
turnstile = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/marketa/Desktop/forks/summer-school-of-solana-2022/6.lesson/turnstile/target/deploy/turnstile-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
